### ISSUE TITLE
Not able to disable caching for teams module

### ISSUE THREAD

**Issue by rameshvk22** [apigee/apigee-edge-drupal#690]
## Steps to Reproduce
Goto configuration-->Apigee Edge-->Teams-->Caching
Set the value to 0 (to disable cache)

## Actual Behavior
When I click on Teams --> Members --> It is throwing the error

The website encountered an unexpected error. Please try again later.
TypeError: Return value of Drupal\apigee_edge_teams\CompanyMembersController::getMembers() must be an instance of Apigee\Edge\Api\Management\Structure\CompanyMembership, null returned in Drupal\apigee_edge_teams\CompanyMembersController->getMembers() (line 97 of modules/composer/apigee_edge/modules/apigee_edge_teams/src/CompanyMembersController.php).
Drupal\apigee_edge_teams\CompanyMembersController->getMembers() (Line: 113)
Drupal\apigee_edge_teams\TeamMembershipManager->getMembers('uber_eats') (Line: 112)
Drupal\apigee_edge_teams\Controller\TeamMembersList->overview(Object)
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 564)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 124)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 158)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 80)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 58)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 708)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

## Expected Behavior
I was hoping to see when I add member it should not be creating 
cache_apigee_edge_teams_company_membership_object

## Screenshots
<img width="1480" alt="Screen Shot 2022-04-28 at 8 13 58 AM" src="https://user-images.githubusercontent.com/6742220/165785777-51ae6143-bd9e-44d3-bbb4-073b7c24eca8.png">

## Version Info
This can be the version you can see on admin/modules in Drupal or 
the output of this command: `composer show`.  Add Drupal core and
other version information if needed.
drupal/core                               9.3.12
drupal/apigee_edge                        2.0.2

**Comment by phdhiren** [comment]
@rameshvk22 
Please update to the latest version, It is resolved in one of earlier releases 
#579

**Comment by phdhiren** [comment]
@rameshvk22 
What is the version of PHP and apigee/apigee-client-php library?

Also, After you set the 0 in cache  expiration, can you clear the Drupal cache once and see any difference.

**Comment by rameshvk22** [comment]
PHP Version  7.4.27
apigee/apigee-client-php   2.0.14
Yes I have cleared  Drupal cache still getting same Error.

**Comment by phdhiren** [comment]
@rameshvk22 

I've tried to replicate it locally, but could not. Can you disable any of the custom code changes and try again?

**Comment by phdhiren** [comment]
@rameshvk22 

I'm able to replicate the issue locally, and will come back with a solution.

**Comment by giteshk** [comment]
@rameshvk22 can you help test the patch in #699 ?
